version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            ls
            cd AVREmulatorTests
            ls
            pwd
            dotnet test
workflows:
  sample: 
    jobs:
      - build-and-test
