version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd AVREmulatorTests
            dotnet test
workflows:
  sample: 
    jobs:
      - build-and-test
